export const BOOTSTRAP_APPLICATION = 'BOOTSTRAP_APPLICATION';
export const BOOTSTRAP_DATA_COMPLETED = 'BOOTSTRAP_DATA_COMPLETED';
export const BOOTSTRAP_DATA_ERROR = 'BOOTSTRAP_DATA_ERROR';

export const CLEAR_RESULTS = 'CLEAR_RESULTS';

export const FETCH_DATA = 'FETCH_DATA';
export const FETCH_DATA_IN_PROGRESS = 'FETCH_DATA_IN_PROGRESS';
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_COMPLETED = 'FETCH_DATA_COMPLETED';